### ISSUE TITLE
Trying to run on Mac

### ISSUE THREAD

**Issue by tuctboh** [tana/pico_usb_sniffer#1]
Mac Mini - Running macOS Monterey (12.7.6)
Brew python in a virtual env - 3.9.6

Copied the UF2 to the Pico, it created /dev/tty.usbmodem146401. If I try to screen, I get all sorts of garbage while using the device. (Logitech S-150 USB Digital Speakers)

lsusb -

```
tuc@Scotts-Mac-mini ~ % lsusb
2024-08-21 09:48:27.485 system_profiler[19499:675761] SPUSBDevice: IOCreatePlugInInterfaceForService failed 0xe00002be
2024-08-21 09:48:27.486 system_profiler[19499:675761] SPUSBDevice: IOCreatePlugInInterfaceForService failed 0xe00002be
Bus 020 Device 003: ID 2109:0817 VIA Labs, Inc. USB3.0 Hub  Serial: 000000000
Bus 020 Device 002: ID 2109:2817 VIA Labs, Inc. USB2.0 Hub  Serial: 000000000
Bus 020 Device 013: ID 2e8a:000a 2e8a Pico  Serial: E6613008E3887B34
Bus 020 Device 015: ID 1130:1620 Tenx Technology, Inc. USB  AUDIO 
Bus 020 Device 019: ID 1d6b:0104 The Linux Foundation BeagleBone  Serial: 1234BBBK5678
Bus 020 Device 010: ID 2f0e:0102 2f0e Fnatic Gear miniSTREAK  Serial: E10E10E0168993FAAC4DE6B50CB1005F
Bus 020 Device 004: ID 05ac:8242 Apple Inc. IR Receiver 
/usr/local/bin/lsusb: line 89: 16#14
14
14: syntax error in expression (error token is "14
14")
Bus 000 Device 006: ID 0a5c
05ac
046d:4500
8289
c52b Broadcom Corp.
Apple Inc.
Logitech Inc. BRCM20702 Hub 
Bus 000 Device 001: ID 1d6b:ILPT Linux Foundation USB 3.0 Bus 
```

```
(venv) tuc@Scotts-Mac-mini tools % python pico_usb_sniffer.py /dev/tty.usbmodem146401
Traceback (most recent call last):
  File "/Users/tuc/WORKSPACE/USBSniffer/pico_usb_sniffer/tools/pico_usb_sniffer.py", line 309, in <module>
    with Sniffer(args.port, args.output) as sniffer:
  File "/Users/tuc/WORKSPACE/USBSniffer/pico_usb_sniffer/tools/pico_usb_sniffer.py", line 235, in __init__
    self.pcap_file = PcapFileWriter(out_path, link_type=PCAP_LINKTYPE_USB_2_0)
  File "/Users/tuc/WORKSPACE/USBSniffer/pico_usb_sniffer/tools/pico_usb_sniffer.py", line 84, in __init__
    self.stream.write(global_header.pack())
TypeError: write() argument must be str, not bytes
```

Thoughts of what i could be?

Tnx

**Comment by tana** [comment]
Sorry for very late response. I was doing different projects and had no time to work on this project.
This bug was fixed by krystofcelba's PR #2 .

**Comment by tana** [comment]
Also, running the script without `-o` option will flood the `stdout` with binary data.
It is recommended to specify output file or pipe to Wireshark.
